#!/usr/bin/env python3
"""
Generate report/sections/_generated_macros.tex from analysis/results_manifest/*.yaml.

Run manually (no CI) as the last step of finalizing a notebook/report section:
    python report/code/generate_macros.py

Every metric in every manifest becomes one \\newcommand, named
\\Metric<CamelCasePhase><CamelCaseMetricName>, with a comment showing the source
manifest key and the SLURM job(s) that produced it (traceability -- see
utilities/reporting/manifest.py for why that matters). main.tex should
\\input{sections/_generated_macros} once; every results/discussion sentence in the
report should cite a macro, never a bare number (see check_no_hand_typed_numbers.py).

A manifest's optional `stability` block (repeated_leakage_safe_eval() output,
see leakage_safe_features.py) is ALSO emitted, as
\\Metric<Phase>Stability<MetricName>Mean / ...Std (both formatted as plain
decimals, 3dp -- these are the statistically honest mean+/-std numbers across
repeated splits and should generally be preferred in report prose over a
single-split headline value). Per-label stability metrics get an extra
<Label> segment: \\Metric<Phase>Stability<MetricName><Label>Mean / ...Std.
"""

import re
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_DIR = REPO_ROOT / "analysis" / "results_manifest"
OUT_FILE = REPO_ROOT / "report" / "sections" / "_generated_macros.tex"


_DIGIT_WORDS = {
    "0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
    "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine",
}


def to_camel(slug: str) -> str:
    """snake_case / kebab-case -> CamelCase, LaTeX-command-safe.

    LaTeX control-sequence names (\\newcommand target) may contain ONLY
    letters -- a digit immediately ends the command name at the tokenizer
    level, so e.g. \\newcommand{\\Metric06Foo}{...} does NOT define a command
    named "Metric06Foo"; it silently corrupts the definition (observed
    2026-09-05: manifest-derived macro text leaking into the compiled PDF as
    visible body text instead of being consumed as \\newcommand calls,
    tracked down to exactly this). Every digit is therefore spelled out
    (e.g. "06" -> "ZeroSix", "f1" -> "FOne") rather than passed through.
    """
    parts = re.split(r"[^A-Za-z0-9]+", slug)
    out = []
    for p in parts:
        if not p:
            continue
        word = "".join(_DIGIT_WORDS.get(ch, ch) for ch in p)
        out.append(word[:1].upper() + word[1:])
    return "".join(out)


def escape_latex(s: str) -> str:
    # Backslash MUST be escaped first -- every other replacement below inserts
    # a literal backslash, and escaping it afterwards would double-escape those.
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
        ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
        ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}"),
    ]
    for k, v in replacements:
        s = s.replace(k, v)
    return s


def main():
    if not MANIFEST_DIR.exists():
        raise SystemExit(f"No manifest directory at {MANIFEST_DIR}")

    manifest_files = sorted(MANIFEST_DIR.glob("*.yaml"))
    if not manifest_files:
        raise SystemExit(f"No manifest .yaml files found in {MANIFEST_DIR}")

    lines = [
        "% AUTO-GENERATED by report/code/generate_macros.py -- DO NOT EDIT BY HAND.",
        "% Source of truth: analysis/results_manifest/*.yaml (git-tracked, human-diffable).",
        "% Regenerate with: python report/code/generate_macros.py",
        "",
    ]

    n_macros = 0
    for mf in manifest_files:
        with open(mf) as f:
            manifest = yaml.safe_load(f)

        phase = manifest["phase"]
        run = manifest["pipeline_run"]
        lines.append(f"% ---- Phase: {phase} "
                      f"(dataset={run.get('dataset_version', '?')}, "
                      f"slurm_job={run.get('slurm_job', '?')}, "
                      f"generated_at={manifest.get('generated_at', '?')}) ----")

        phase_camel = to_camel(phase)
        for metric_name, m in manifest["metrics"].items():
            cmd_name = f"\\Metric{phase_camel}{to_camel(metric_name)}"
            display = m.get("display", str(m.get("value")))
            label = m.get("label", metric_name)
            lines.append(
                f"\\newcommand{{{cmd_name}}}{{{escape_latex(str(display))}}} "
                f"% {escape_latex(label)} -- manifest key: {phase}.{metric_name}"
            )
            n_macros += 1

        stability = manifest.get("stability")
        if stability:
            # Avoid "...StabilityStability..." when the phase slug already
            # ends in "_stability" (most stability-harness manifests do).
            stability_infix = "" if phase_camel.endswith("Stability") else "Stability"
            for metric_name, m in stability.get("metrics", {}).items():
                metric_camel = to_camel(metric_name)
                if "per_label" in m:
                    for label, s in m["per_label"].items():
                        label_camel = to_camel(label)
                        for stat in ("mean", "std"):
                            cmd_name = f"\\Metric{phase_camel}{stability_infix}{metric_camel}{label_camel}{stat.capitalize()}"
                            lines.append(
                                f"\\newcommand{{{cmd_name}}}{{{s[stat]:.3f}}} "
                                f"% {escape_latex(metric_name)} [{escape_latex(label)}] {stat} across "
                                f"{stability.get('n_repeats', '?')} repeats -- manifest key: {phase}.stability.{metric_name}.per_label.{label}"
                            )
                            n_macros += 1
                elif "mean" in m:
                    for stat in ("mean", "std"):
                        cmd_name = f"\\Metric{phase_camel}{stability_infix}{metric_camel}{stat.capitalize()}"
                        lines.append(
                            f"\\newcommand{{{cmd_name}}}{{{m[stat]:.3f}}} "
                            f"% {escape_latex(metric_name)} {stat} across "
                            f"{stability.get('n_repeats', '?')} repeats -- manifest key: {phase}.stability.{metric_name}"
                        )
                        n_macros += 1
        lines.append("")

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_FILE} ({n_macros} macros from {len(manifest_files)} manifest files)")


if __name__ == "__main__":
    main()
